name: Build and Publish Docker Images

on:
  push:
    branches:
      - docker_fix

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/docker_fix' # Running this job only for docker_fix branch

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Set lowercase repository owner
        run: echo "LOWERCASE_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # Step 1: Build and Publish CUDA 12.1 Docker image
      - name: Build and Publish CUDA 12.1 Docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into GitHub Packages
          image-name: ctrlaltdiffuse-cuda12 # Provide Docker image name
          image-owner: ${{ env.LOWERCASE_OWNER }} # Use lowercase repository owner
          dockerfile: ./docker/Dockerfile # Path to your Dockerfile
          build-args: CUDA_VERSION=12.1 # CUDA 12.1 build argument

      # Step 2: Build and Publish CUDA 11.8 Docker image
      - name: Build and Publish CUDA 11.8 Docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into GitHub Packages
          image-name: ctrlaltdiffuse-cuda11 # Provide Docker image name
          image-owner: ${{ env.LOWERCASE_OWNER }} # Use lowercase repository owner
          dockerfile: ./docker/Dockerfile # Path to your Dockerfile
          build-args: CUDA_VERSION=11.8 # CUDA 11.8 build argument
