name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push CUDA 12 Docker image
      - name: Build and push CUDA 12 image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ctrlaltdiffuse-cuda12:latest -f docker/Dockerfile.cuda12 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ctrlaltdiffuse-cuda12:latest

      # Build and push CUDA 11 Docker image
      - name: Build and push CUDA 11 image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ctrlaltdiffuse-cuda11:latest -f docker/Dockerfile.cuda11 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ctrlaltdiffuse-cuda11:latest
