name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push CUDA 12.1 Docker image
      - name: Build and push CUDA 12.1 image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ctrlaltdiffuse-cuda12:latest --build-arg CUDA_VERSION=12.1 -f docker/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ctrlaltdiffuse-cuda12:latest

      # Build and push CUDA 11.8 Docker image
      - name: Build and push CUDA 11.8 image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ctrlaltdiffuse-cuda11:latest --build-arg CUDA_VERSION=11.8 -f docker/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ctrlaltdiffuse-cuda11:latest
