name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set lowercase repository owner
        run: echo "LOWERCASE_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # Step 1: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Step 2: Build and push CUDA 12.1 Docker image
      - name: Build and push CUDA 12.1 image
        run: |
          docker build --build-arg CUDA_VERSION=12.1 -t ghcr.io/${{ env.LOWERCASE_OWNER }}/ctrlaltdiffuse-cuda12:latest -f ./docker/Dockerfile .
          docker push ghcr.io/${{ env.LOWERCASE_OWNER }}/ctrlaltdiffuse-cuda12:latest

      # Step 3: Build and push CUDA 11.8 Docker image
      - name: Build and push CUDA 11.8 image
        run: |
          docker build --build-arg CUDA_VERSION=11.8 -t ghcr.io/${{ env.LOWERCASE_OWNER }}/ctrlaltdiffuse-cuda11:latest -f ./docker/Dockerfile .
          docker push ghcr.io/${{ env.LOWERCASE_OWNER }}/ctrlaltdiffuse-cuda11:latest
